# Generated by Django 3.0.6 on 2020-05-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('active_cases', models.IntegerField(default=0)),
                ('dead_cases', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dead', 'Dead')], max_length=6)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidcases.Country')),
            ],
        ),
    ]
